services:
  app:
    container_name: portfolio
    build:
      context: .
      args:
        - NEXT_PUBLIC_DISCORD_ID=${NEXT_PUBLIC_DISCORD_ID}
    image: portfolio-app
    restart: unless-stopped
    env_file:
      - ./.env
    networks:
      - caddy
    labels:
      caddy: "handokota.com, www.handokota.com"
      caddy.@www.host: "www.handokota.com"
      caddy.redir: "@www https://handokota.com{uri}"
      caddy.reverse_proxy: "{{upstreams 3000}}"

      com.centurylinklabs.watchtower.enable: "false"

networks:
  caddy:
    external: true